### ISSUE TITLE
Downloading owasp artifact from bintray results in 403 forbidden

### ISSUE THREAD

**Issue by zdelagrange** [jhermann/dependency-check-py#7]
Is it possible the permissions on the storage was changed?

```Downloading 'https://bintray.com/artifact/download/jeremy-long/owasp/dependency-check-5.2.2-release.zip'...

Traceback (most recent call last):

  File "/tmp/py3env/bin/dependency-check", line 8, in <module>

    sys.exit(run())

  File "/tmp/py3env/lib/python3.6/site-packages/dependency_check.py", line 110, in run

    dc_command = install()

  File "/tmp/py3env/lib/python3.6/site-packages/dependency_check.py", line 63, in install

    with closing(urlopen(dc_url)) as url_handle:

  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen

    return opener.open(url, data, timeout)

  File "/usr/lib/python3.6/urllib/request.py", line 532, in open

    response = meth(req, response)

  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response

    'http', request, response, code, msg, hdrs)

  File "/usr/lib/python3.6/urllib/request.py", line 564, in error

    result = self._call_chain(*args)

  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain

    result = func(*args)

  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302

    return self.parent.open(new, timeout=req.timeout)

  File "/usr/lib/python3.6/urllib/request.py", line 532, in open

    response = meth(req, response)

  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response

    'http', request, response, code, msg, hdrs)

  File "/usr/lib/python3.6/urllib/request.py", line 570, in error

    return self._call_chain(*args)

  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain

    result = func(*args)

  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default

    raise HTTPError(req.full_url, code, msg, hdrs, fp)

urllib.error.HTTPError: HTTP Error 403: Forbidden
```

**Comment by jhermann** [comment]
Works for me. You mention 0 versions.

**Comment by jhermann** [comment]
Bintray introduced (monthly) rate limits -- that is why it worked for me on Aug 1. 

0.6.0 will use the new GH hosting, so that should be a permanent fix.

**Comment by jhermann** [comment]
Upstream issue: https://github.com/jeremylong/DependencyCheck/issues/2843

**Comment by AbdealiLoKo** [comment]
When using this package, I get a 404 for the bintray URL

**Comment by jhermann** [comment]
Well, seems I somehow forgot about the 0.6.0 release. If you need an immediate fix, deploy the current head via the GH repo zip link. I put the new release on my TODO.
