### ISSUE TITLE
dependency check 404 error

### ISSUE THREAD

**Issue by tejaschumbalkar** [jhermann/dependency-check-py#8]
Hello,

Running dependency check using 
```
dependency-check --disableAssembly -s / -o build
```

results in the below error:

```
root:/# dependency-check --disableAssembly -s / -o build

Downloading 'https://bintray.com/artifact/download/jeremy-long/owasp/dependency-check-5.2.4-release.zip'...
Traceback (most recent call last):
  File "/opt/conda/bin/dependency-check", line 8, in <module>
    sys.exit(run())
  File "/opt/conda/lib/python3.6/site-packages/dependency_check.py", line 110, in run
    dc_command = install()
  File "/opt/conda/lib/python3.6/site-packages/dependency_check.py", line 63, in install
    with closing(urlopen(dc_url)) as url_handle:
  File "/opt/conda/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/opt/conda/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found
```

*Installation method*
```
pip install dependency-check
```

**Comment by vroetman** [comment]
This is because JFrog has sunset their bintray service.

According to https://owasp.org/www-project-dependency-check/ we can get the [latest release](https://github.com/jeremylong/DependencyCheck/releases/download/v6.2.2/dependency-check-6.2.2-release.zip) or [other releases](https://github.com/jeremylong/DependencyCheck/releases) from github.

Oh, I see it's been fixed in master, but there has not been a release of dependency-check-py since `0.5.0`, so the [pypi release](https://pypi.org/project/dependency-check/) is still broken.

@jhermann, could you please do another release and update the pypi package?

**Comment by jhermann** [comment]
https://pypi.org/project/dependency-check/0.6.0/
